[features]
seeds = false
skip-lint = false
[programs.localnet]
hello_world = "FVUkr6SMAU3EjsW9v2A6eZYRrSyqfqkUEVHiwswEvCZG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/elijah/SDCcPraNtvK4XPk5XASqYExWyEPrH9YAnEwm6Hcuz3U.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
